techs:
  flow_cap_new_max:
    $ref: "#/$defs/TechParamNullNumber"
    default: .inf
    x-type: float
    title: Maximum new flow capacity.
    description: >-
      Maximum amount of flow capacity of a specific technology vintage.
    x-unit: power.

  storage_cap_new_max:
    $ref: "#/$defs/TechParamNullNumber"
    default: .inf
    x-type: float
    title: Maximum new storage capacity.
    description: >-
      Maximum amount of storage capacity of a specific technology vintage.
    x-unit: energy.

  source_cap_new_max:
    $ref: "#/$defs/TechParamNullNumber"
    default: .inf
    x-type: float
    title: Maximum new source capacity.
    description: >-
      Maximum amount of source capacity of a specific technology vintage.
    x-unit: power.

  area_use_new_max:
    $ref: "#/$defs/TechParamNullNumber"
    default: .inf
    x-type: float
    title: Maximum new area use.
    description: >-
      Maximum amount of area use of a specific technology vintage.
    x-unit: area.

  available_initial_cap:
    $ref: "#/$defs/TechParamNullNumber"
    default: 0
    x-type: float
    title: The per-investment step fraction of initial capacity that is still available.
    description: >-
      Removes the defined fraction of initial capacity (`flow_cap_initial`, `storage_cap_initial`, etc.) in each investstep.
      This is usually defined over the `investsteps` dimension to provide different fractions (ultimately adding up to 1) per investment step.
    x-unit: fraction.

  available_vintages:
    $ref: "#/$defs/TechParamNullNumber"
    default: 0
    x-type: float
    title: The per-investment step fraction of new capacity being decommissioned.
    description: >-
      Removes the defined fraction of initial capacity (`flow_cap_initial`, `storage_cap_initial`, etc.) in each investstep.
      This is usually defined over the `investsteps` dimension to provide different fractions (ultimately adding up to 1) per investment step.
    x-unit: fraction.

  flow_cap_initial:
    $ref: "#/$defs/TechParamNullNumber"
    default: 0
    x-type: float
    title: Initial / existing flow capacity in pathway optimisation.
    description: >-
      Sets `flow_cap` lower bound in first investment period during pathway optimisation.
    x-unit: power.

  area_use_initial:
    $ref: "#/$defs/TechParamNullNumber"
    default: 0
    x-type: float
    title: Initial / existing area use in pathway optimisation.
    description: >-
      Sets `area_use` lower bound in first investment period during pathway optimisation.
    x-unit: $\text{area}^{2}$.

  storage_cap_initial:
    $ref: "#/$defs/TechParamNullNumber"
    default: 0
    x-type: float
    title: Initial / existing storage capacity in pathway optimisation.
    description: >-
      Sets `storage_cap` lower bound in first investment period during pathway optimisation.
    x-unit: energy.

  source_cap_initial:
    $ref: "#/$defs/TechParamNullNumber"
    default: 0
    x-type: float
    title: Initial / existing source capacity in pathway optimisation.
    description: >-
      Sets `source_cap` lower bound in first investment period during pathway optimisation.
    x-unit: power.

  flow_cap_new_max_rate:
    $ref: "#/$defs/TechParamNullNumber"
    default: .inf
    x-type: float
    title: Rate of new flow capacity deployment.
    description: >-
      Sets limit on new flow capacity deployment relative to total capacity in previous investment step.
    x-unit: fraction.

parameters:

  investstep_resolution:
    $ref: "#/$defs/TechParamNullNumber"
    default: 1
    x-type: float
    title: Per-investment step weighting.
    description: >-
      The weighting to give to each investment-step in the objective function.
      This usually refers to the number of years that one investment step represents (e.g. 10 years for the steps [2030, 2040, 2050]).
    x-unit: years.